# Generated by Django 2.2.10 on 2022-06-17 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customers',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalcustomers',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
