# Generated by Django 2.2.10 on 2022-06-17 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0002_auto_20220617_0822'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customers',
            old_name='firs_tname',
            new_name='firs_name',
        ),
        migrations.RenameField(
            model_name='historicalcustomers',
            old_name='firs_tname',
            new_name='firs_name',
        ),
    ]
