# Generated by Django 2.2.10 on 2022-06-17 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0003_auto_20220617_0825'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customers',
            old_name='firs_name',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='historicalcustomers',
            old_name='firs_name',
            new_name='first_name',
        ),
    ]
