# Generated by Django 2.2.10 on 2022-06-17 08:35

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user_management', '0004_auto_20220617_0826'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HistoricalCustomers',
            new_name='HistoricalUsers',
        ),
        migrations.RenameModel(
            old_name='Customers',
            new_name='Users',
        ),
        migrations.AlterModelOptions(
            name='historicalusers',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical users'},
        ),
    ]
