# Generated by Django 2.2.10 on 2022-06-17 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0005_auto_20220617_0835'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HistoricalUsers',
        ),
    ]
