# Generated by Django 2.2.10 on 2022-06-17 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0006_delete_historicalusers'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Users',
            new_name='Customers',
        ),
    ]
