# Generated by Django 2.2.10 on 2022-06-17 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0007_auto_20220617_0850'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customers',
            old_name='first_name',
            new_name='firstname',
        ),
        migrations.RenameField(
            model_name='customers',
            old_name='first_verification',
            new_name='last_login',
        ),
        migrations.RenameField(
            model_name='customers',
            old_name='last_name',
            new_name='lastname',
        ),
        migrations.RenameField(
            model_name='customers',
            old_name='middle_name',
            new_name='middlename',
        ),
    ]
