# Generated by Django 2.2.10 on 2022-06-17 09:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0008_auto_20220617_0858'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customers',
            name='city',
        ),
        migrations.RemoveField(
            model_name='customers',
            name='country',
        ),
        migrations.RemoveField(
            model_name='customers',
            name='state',
        ),
        migrations.CreateModel(
            name='Residential_address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_management.Customers')),
            ],
        ),
    ]
