# Generated by Django 2.2.10 on 2022-06-17 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0009_auto_20220617_0951'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customers',
            name='zip',
        ),
        migrations.AddField(
            model_name='residential_address',
            name='zip',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
